### ISSUE TITLE
Can't select mycroft-core install dir

### ISSUE THREAD

**Issue by jorgesca** [lolstring/gnome-shell-extension-mycroft#1]
Hi, I just installed mycroft-core and then this extension. When I try to configure the location of mycroft-core in the extensions' settings window I select 'other', which normally opens a file selection window to allow the user to select a directory. Nothing happens here, though, and the extension config window seems to freeze. Is there a way to specify this location manually?

**Comment by jorgesca** [comment]
Sorry, I forgot to add additional information. This is arch linux, gnome 3.22.2. Is there is anything else I should provide, please ask.

**Comment by lolstring** [comment]
Hey, 

Could you try this - after the file selection window is open and you are in the directory of mycroft-core there will be a "Select Folder" button typically on the bottom right corner with the "Cancel" Button. Click the "Select Folder" button

If that doesn't work can you run this before you open the config window and perform the task and provide me the output   - 

 * `journalctl /usr/bin/gnome-shell-extension-prefs -f -o cat`
 * Open dconf-editor traverse into  **/org/gnome/shell/extensions/mycroft@rahul.io** and see if the **mycroft-core-location** is being set after clicking "Select Folder"

Hacky way of setting it until I can figure the issue out is from changing the value in dconf editor in **/org/gnome/shell/extensions/mycroft@rahul.io**  - 

**mycroft-core-location**, 

make sure that these are the values

**mycroft-install-type** --  **'0'** or **'2'**,  
**mycroft-is-intall** -- **true**


Thanks
