### ISSUE TITLE
Mycroft is Active: Nothing happens

### ISSUE THREAD

**Issue by mil1i** [lolstring/gnome-shell-extension-mycroft#14]
So I have Mycroft-core installed and it starts. I hear the voice speak as it starts. I see it start when I run from CLI "./mycroft start", as well when I press the Play button from the Mycrosoft AI Assistant. HOWEVER, when I type anything in nothing happens. I've tried asking the weather, the date, and just typing "Hi". Below is a screenshot. Any ideas?

![mycroft](https://user-images.githubusercontent.com/8459426/28553740-57a0db82-70aa-11e7-95bb-5ffb2bfabe02.png)

**Comment by AIIX** [comment]
Does it work when you try speak to it like "Hey Mycroft, tell me a joke" or something like does it respond when using the CLI client ?

**Comment by yyyyuuu** [comment]
same question again
