### ISSUE TITLE
Correct mycroft-core path, IP and Port have been set, but extension does not activate Mycroft

### ISSUE THREAD

**Issue by fcoclavero** [lolstring/gnome-shell-extension-mycroft#16]
On Ubuntu Gnome 17.04.

**Comment by olymk2** [comment]
Also happens on ubuntu 17.10, mycroft installed from the applet script.

Press play button and it turns purple saying started but never starts.

**Comment by AIIX** [comment]
Refer to my last reply here: https://github.com/lolstring/gnome-shell-extension-mycroft/issues/5

**Comment by olymk2** [comment]
well that sucks, although i don't experience any freezing just it never connecting.
