### ISSUE TITLE
REQ: Connect to a remote mycroft instance via websockets

### ISSUE THREAD

**Issue by chrisvella** [lolstring/gnome-shell-extension-mycroft#2]
This would allow paring with a remote instance of mycroft in the same manner as the android client.

**Comment by lolstring** [comment]
Will add support for IP and Port number in the next release or so.

**Comment by chrisvella** [comment]
Awesome :)


Sent on the go with Vodafone
-------- Original message --------From: Rahul Mehra <notifications@github.com> Date: 21/4/17  11:55 am  (GMT+10:00) To: lolstring/gnome-shell-extension-mycroft <gnome-shell-extension-mycroft@noreply.github.com> Cc: chrisvella <chrisvella94@gmail.com>, Author <author@noreply.github.com> Subject: Re: [lolstring/gnome-shell-extension-mycroft] REQ: Connect to a remote mycroft instance via websockets (#2) 
Will add support for IP and Port number in the next release or so.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lolstring/gnome-shell-extension-mycroft","title":"lolstring/gnome-shell-extension-mycroft","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lolstring/gnome-shell-extension-mycroft"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lolstring in #2: Will add support for IP and Port number in the next release or so."}],"action":{"name":"View Issue","url":"https://github.com/lolstring/gnome-shell-extension-mycroft/issues/2#issuecomment-296011842"}}}

**Comment by lolstring** [comment]
Hey. 

I have updated this git with remote ip support. I am not pushing this just yet to extensions.gnome.org. 

You can download the zip of the extension from the DIST folder and install it from tweak tools. 

If you face any errors let me know. I am keeping this open for another day in case an error pops up.
