### ISSUE TITLE
ubuntu 19.10

### ISSUE THREAD

**Issue by EndrII** [lolstring/gnome-shell-extension-mycroft#24]
do not work in ubuntu 19.10 
gnome 3.34
fix please

**Comment by krisgesling** [comment]
Hi Endrll, I don't believe this extension is in a working state for any distribution. 

It is a Community contributed extension and not something that Mycroft has capacity to maintain. So if anyone reading along is interested in helping out, please come and say hi here or in [Mycroft Chat](https://chat.mycroft.ai/community/channels/desktop)

**Comment by EndrII** [comment]
ok 
if I have time, I'll see for myself what could be the problem there.
