### ISSUE TITLE
Can't start Mycroft Assistant 

### ISSUE THREAD

**Issue by misfim** [lolstring/gnome-shell-extension-mycroft#3]
This is my first issue on Github so sorry for any misunderstanding. I successfully compile and install mycroft-core, but now i can't activate assistant. It takes almost 10 minutes and fails anyway, moreover it also crashes gnome-shell, forcing it to reload. Is there any way to start this assistant from terminal to see what's going on?

**Comment by lolstring** [comment]
Can you provide more details about your system ? 

run 
`journalctl /usr/bin/gnome-shell -f -o cat > ~/Desktop/gnome-shell.log` 

Restart your shell by Alt+f2  then type 'r' and 'enter'

Try starting the service. If it hangs or fails, please provide me the log file of your gnome-shell activity on your desktop. Delete it later.

The following procedure is not required and could be done through the extension but 
to start the service manually (No extension). 

Open terminal. Go to your mycroft-core installation folder.  Run - 
`./mycroft.sh start` in a new window.
After service, skill, voice and cli have started
`screen -r mycroft-cli`
Type something into CLI. 

You will then get an access code (6 Characters). Hear/read the statement in the CLI carefully. After getting the access code. Go to home.mycroft.ai. Sign Up. Then go into devices. Add a device and  fill in the details. You could then . 
`./mycroft.sh stop`

Setup the Mycroft core location folder in the extension settings page and then start the service from the extension. If your shell hangs log please provide me the log file.

**Comment by OpnSrcConstruction** [comment]
Did you make sure and browse into the mycroft-core folder, and select-folder before starting the extension? You may have to re-start your shell.
