### ISSUE TITLE
"Your Mycroft Assistant is currently disabled"

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [lolstring/gnome-shell-extension-mycroft#4]
I installed this amazing extension from the gnome extensions website, and finally installed mycroft core through the installer in this, but sadly even after rebooting & changing my "installation type" in the settings of this extension, the extension doesn't work. it simply says "Your Mycroft Assistant is currently disabled"

now when i go to the Mycroft-core folder, i can easily run "./mycroft start" and it works, but it says it needs a pairing code or something. i searched this issue for hours, yet all the guides i tried didn't work. even without the extension, i cannot get mycroft to give this "pairing code" or even work. and this extension doesnt budge. please fix this, amazing devs!!

**Comment by AIIX** [comment]
Check the following: 
1.) Can you see any skills folders exist inside /opt/mycroft/skills/
2.) Does mycroft work via CLI using ./mycroft.sh start from inside the mycroft folder
3.) When selecting the mycroft core folder be sure to double click inside the folder before pressing select

**Comment by afranke** [comment]
I had the same issue and https://community.mycroft.ai/t/pairing-on-arch-linux-resolved/1549 helped me (even though I’m using Fedora). From the Mycroft-core directory try running `./msm/msm default` and restart Mycroft.

**Comment by DoudouJack** [comment]
Hello, I'm having the same issue ("Your Mycroft Assistant is currently disabled") however, MyCroft is fully functional on my machine (skills are working as well).
I installed MyCroft via GIT repository, in the extension I set the path to mycroft-core and left the IP and port as default. What am I missing? 
Thanks a lot for the extension, looks really great!

**Comment by AIIX** [comment]
DoudouJack please post your gnome-shell log of when you try to connect the extension.

**Comment by DoudouJack** [comment]
Where can I find it? Is it the xsession log? thank you very much in advance. (Ubuntu 17.10 - gnome-shell 3.26.2)

**Comment by GNOME-IS-LIFE** [comment]
stupid me I forgot to close this issue as I now use elementary OS (no more gnome shell!)
